services:
  - type: web
    name: email-manager-backend-nuevo
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: "cd backend && pip install -r requirements-prod.txt"
    startCommand: "cd backend && python run.py"
    healthCheckPath: "/api/health"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://usuario:password@host:puerto/database
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_TENANT_ID
        sync: false
      - key: MICROSOFT_REDIRECT_URI
        value: https://email-manager-backend-nuevo.onrender.com/auth/callback
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_MAX_TOKENS
        value: "1000"
      - key: OPENAI_TEMPERATURE
        value: "0.3"
