[build]
builder = "nixpacks"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { FLASK_ENV = "production" }
